theme: jekyll-theme-slate
title: The Sun Now!
description: View the current Sun from different satellite observatories
github:
  is_project_page: false
# google_analytics: UA-222104143-1
# Analytics
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : G-H475M2Z4P6
    anonymize_ip         : true # true, false (default)
